HTTP/1.1 400 Bad Request
Content-Type: application/json;charset=UTF-8
Cache-Control: no-store
Pragma: no-cache

{
  "error":"invalid_request",
  "error_description":"example",
  "error_uri":"https://example.com/error"
}
