HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Cache-Control: no-store
Pragma: no-cache

{
  "access_token":"aaaaaaaa",
  "token_type":"bearer",
  "expires_in":3600,
  "refresh_token":"bbbbbbbb",
  "scope":"example"
}
